### ISSUE TITLE
epeg_open_header failes for some jpgs

### ISSUE THREAD

**Issue by manuelstofer** [mattes/epeg#11]
The iteration over im->in.jinfo.marker_list seems to be broken.
https://github.com/mattes/epeg/blob/master/src/lib/epeg_main.c#L838

This return statement returns always after the first marker.
https://github.com/mattes/epeg/blob/master/src/lib/epeg_main.c#L902

**Comment by manuelstofer** [comment]
Made a pull request https://github.com/mattes/epeg/pull/12, so I'm closing this.

**Comment by mattes** [comment]
Thanks!
